/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DataStats: typeof import('./components/DataStats.vue')['default']
    DataVisualizationDemo: typeof import('./components/DataVisualizationDemo.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    TextSpirit: typeof import('./components/TextSpirit.vue')['default']
  }
}
